### ISSUE TITLE
Fix GitHub Actions pytest for pre-3.11

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/civic-scraper#179]
Pytest is failing on GitHub Actions CI/CD test run for all versions of Python earlier than 3.11.

Unable to duplicate the errors on 3.8-3.11 locally (ie all tests run fine), so this feels like a GH Actions issue...

Disabled tests for earlier versions to get back to green

```
Traceback (most recent call last):
  File "/home/runner/.local/share/virtualenvs/civic-scraper-laP-GJso/bin/pytest", line 5, in <module>
    from pytest import console_main
  File "/home/runner/.local/share/virtualenvs/civic-scraper-laP-GJso/lib/python3.10/site-packages/pytest/__init__.py", line 5, in <module>
    from _pytest._code import ExceptionInfo
  File "/home/runner/.local/share/virtualenvs/civic-scraper-laP-GJso/lib/python3.10/site-packages/_pytest/_code/__init__.py", line 3, in <module>
    from .code import Code
  File "/home/runner/.local/share/virtualenvs/civic-scraper-laP-GJso/lib/python3.10/site-packages/_pytest/_code/code.py", line 56, in <module>
    from exceptiongroup import BaseExceptionGroup
ModuleNotFoundError: No module named 'exceptiongroup'
```

**Comment by zstumgoren** [comment]
Update the GH Action step to pip install an `ExceptionGroup` backport appears to have resolved the build error for pre-3.11 versions. Dropped official support for 3.7 and now testing against 3.8-3.11.
