### ISSUE TITLE
CivicScraper content-length bug

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/civic-scraper#58]
Alameda County and a number of other CivicPlus sites are throwing below `KeyError`. See [here][] for full list of affected counties.

[here]: https://docs.google.com/spreadsheets/d/1dSKb_UFIuryXaIdyPrZMQB4wuowQrPk75QZRQi_GxVk/edit?usp=sharing

```
    assets = site.scrape(start_date='2020-06-01', end_date='2020-06-30')
  File "/Users/tumgoren/.pyenv/versions/test-civic-scraper/lib/python3.8/site-packages/civic_scraper/scrapers/civicplus.py", line 108, in scrape
    metadata = self._get_metadata(links)
  File "/Users/tumgoren/.pyenv/versions/test-civic-scraper/lib/python3.8/site-packages/civic_scraper/scrapers/civicplus.py", line 165, in _get_metadata
    asset_args['content_length'] = headers['content-length']
  File "/Users/tumgoren/.pyenv/versions/test-civic-scraper/lib/python3.8/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
```

**Comment by zstumgoren** [comment]
This bug *is* valid and will need to be fixed as part of the `refactor` branch. Verified against [Humboldt County](http://ca-humboldtcounty.civicplus.com/AgendaCenter) using the cli:

```
civic-scraper scrape -c -d -s 2020-06-01 -e 2020-06-30 --url http://ca-humboldtcounty.civicplus.com/AgendaCenter
12-25 15:01 - civic_scraper.runner - Scraping 1 site(s) from 2020-06-01 to 2020-06-30...
12-25 15:01 - civic_scraper.runner - 	http://ca-humboldtcounty.civicplus.com/AgendaCenter
12-25 15:01 - civic_scraper.platforms.civic_plus.site - Cached search results page HTML: /Users/tumgoren/.civic-scraper/artifacts/https__ca-humboldtcounty.civicplus.com__AgendaCenter__Search__QUERYterm=&CIDs=all&startDate=06%2F01%2F2020&endDate=06%2F30%2F2020&dateRange=&dateSelector=
Traceback (most recent call last):
  File "/Users/tumgoren/.pyenv/versions/test-civic-scraper/bin/civic-scraper", line 33, in <module>
    sys.exit(load_entry_point('civic-scraper', 'console_scripts', 'civic-scraper')())
  File "/Users/tumgoren/.pyenv/versions/3.8.4/envs/test-civic-scraper/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tumgoren/.pyenv/versions/3.8.4/envs/test-civic-scraper/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/tumgoren/.pyenv/versions/3.8.4/envs/test-civic-scraper/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tumgoren/.pyenv/versions/3.8.4/envs/test-civic-scraper/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tumgoren/.pyenv/versions/3.8.4/envs/test-civic-scraper/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/tumgoren/code/stanford/biglocal/civic-scraper/civic_scraper/cli.py", line 96, in scrape
    runner.scrape(**kwargs)
  File "/Users/tumgoren/code/stanford/biglocal/civic-scraper/civic_scraper/runner.py", line 74, in scrape
    _collection = site.scrape(
  File "/Users/tumgoren/code/stanford/biglocal/civic-scraper/civic_scraper/platforms/civic_plus/site.py", line 70, in scrape
    assets = self._build_asset_collection(file_metadata)
  File "/Users/tumgoren/code/stanford/biglocal/civic-scraper/civic_scraper/platforms/civic_plus/site.py", line 151, in _build_asset_collection
    'content_type': headers['content-type'],
  File "/Users/tumgoren/.pyenv/versions/3.8.4/envs/test-civic-scraper/lib/python3.8/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'
```

**Comment by zstumgoren** [comment]
No longer able to reproduce this bug on the `refactor` branch. Tried with two counties that were previously raising the errors and they worked. Closing for now.

```
civic-scraper scrape -c -d -s 2020-06-01 -e 2020-06-30 --url http://ca-marina.civicplus.com/AgendaCenter
civic-scraper scrape -c -d -s 2020-06-01 -e 2020-06-30 --url http://ca-montereypark.civicplus.com/AgendaCenter
```
