### ISSUE TITLE
CivicPlus "aria-label" parsing bug

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/civic-scraper#60]
[Artesia](http://ca-artesia.civicplus.com/AgendaCenter) throwing what appears to be a parsing-related error when called as below:

```
 assets = site.scrape(start_date='2020-06-01', end_date='2020-06-30')
```

```
Traceback (most recent call last):
  File "civicplus_test_MNOACK.py", line 40, in <module>
    print("unsuccessful")
  File "/Users/tumgoren/.pyenv/versions/test-civic-scraper/lib/python3.8/site-packages/civic_scraper/scrapers/civicplus.py", line 99, in scrape
    post_params = self._get_post_params(soup, start_date, end_date)
  File "/Users/tumgoren/.pyenv/versions/test-civic-scraper/lib/python3.8/site-packages/civic_scraper/scrapers/civicplus.py", line 213, in _get_post_params
    meeting_name = element['aria-label'].strip()
  File "/Users/tumgoren/.pyenv/versions/test-civic-scraper/lib/python3.8/site-packages/bs4/element.py", line 1406, in __getitem__
    return self.attrs[key]
KeyError: 'aria-label'
```

**Comment by zstumgoren** [comment]
Resolved (i.e. not reproducible) in `refactor` branch
