### ISSUE TITLE
Scraper fails on some CivicPlus sites

### ISSUE THREAD

**Issue by DiPierro** [biglocalnews/civic-scraper#91]
`civic-scraper` crashes when `site.scrape` is called on a few URLS, including this one in Colorado:

```
url = 'http://co-routtcounty.civicplus.com/AgendaCenter'
site = CivicPlusSite(url)
assets = site.scrape()
```

Here's the error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/civic_scraper/platforms/civic_plus/site.py", line 70, in scrape
    file_metadata = self.parser_kls(raw_html).parse()
  File "/opt/homebrew/lib/python3.9/site-packages/civic_scraper/platforms/civic_plus/parser.py", line 21, in parse
    metadata = self._extract_asset_data(divs)
  File "/opt/homebrew/lib/python3.9/site-packages/civic_scraper/platforms/civic_plus/parser.py", line 44, in _extract_asset_data
    cmte_name = self._committee_name(div)
  File "/opt/homebrew/lib/python3.9/site-packages/civic_scraper/platforms/civic_plus/parser.py", line 71, in _committee_name
    div.h2.span.extract()
AttributeError: 'NoneType' object has no attribute 'span'
```

The same error message appears for:
* ct-bristol.civicplus.com
* https://www.acwd.org/AgendaCenter
* http://co-archuletacounty.civicplus.com/AgendaCenter
* http://co-summitcounty.civicplus.com/AgendaCenter
* http://fl-jupiter.civicplus.com/AgendaCenter
* http://fl-northpalmbeach.civicplus.com/AgendaCenter
* http://il-roselle.civicplus.com/AgendaCenter
*  http://mn-ardenhills.civicplus.com/AgendaCenter
* http://mn-washingtoncounty.civicplus.com/AgendaCenter
* http://nv-nyecounty.civicplus.com/AgendaCenter
* http://ny-victor.civicplus.com/AgendaCenter
* http://oh-athens.civicplus.com/AgendaCenter
* http://oh-fultoncounty.civicplus.com/AgendaCenter
* http://tx-fredericksburg.civicplus.com/AgendaCenter
* http://wa-monroe.civicplus.com/AgendaCenter

Let's diagnose why this is crashing and find a fix.

**Comment by zstumgoren** [comment]
Fixed in #176
